import type { Metadata } from "next";
import Link from "next/link";
import { LegalLayout } from "@/components/legal-layout";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Terms for Protein Pic, including Apple in-app purchases, the free trial, and acceptable use.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main id="main">
        <LegalLayout title="Terms of Use" updated="September 4, 2026">
          <p>
            These Terms of Use ("Terms") govern your use of the Protein Pic iOS
            app and the marketing site at proteinpic.app. The app is published
            by {site.seller}. By downloading or using Protein Pic, you agree to
            these Terms. If you do not agree, do not use the app.
          </p>
          <p>
            Privacy details live on the <Link href="/privacy">Privacy Policy</Link>.
          </p>

          <h2>The app</h2>
          <p>
            Protein Pic helps you estimate protein from a meal photo, barcode,
            or menu scan, then track a daily protein target, streaks, and
            optional groups. It also offers coach suggestions and can read
            Apple Health workout data if you allow it.
          </p>
          <p>
            Protein counts are estimates generated by software. They can be
            wrong. You can edit a result before you save it. The app is a
            tracking tool, not medical care, not a diagnostic device, and not a
            substitute for a doctor, dietitian, or pharmacist. If you use a
            GLP-1 medicine or have a medical condition, follow your clinician's
            guidance. Protein Pic does not prescribe, dose, or manage
            medication.
          </p>

          <h2>Eligibility</h2>
          <p>
            You must be old enough to accept these Terms in your region and
            able to hold an Apple ID. The app requires iOS 15.1 or later.
          </p>

          <h2>License</h2>
          <p>
            We grant you a personal, non-exclusive, non-transferable license to
            use Protein Pic on Apple devices you own or control, as allowed by
            the App Store terms. You may not copy, reverse engineer, or
            resell the app except as law allows.
          </p>

          <h2>Apple in-app purchases</h2>
          <p>
            Protein Pic is free to download and start. Some features require a
            subscription sold as an Apple in-app purchase:
          </p>
          <ul>
            <li>A {site.pricing.trial} when offered</li>
            <li>ProteinPic Monthly at {site.pricing.monthly}</li>
            <li>ProteinPic Annual at {site.pricing.yearly}</li>
          </ul>
          <p>
            Prices are in US dollars on the US App Store and may differ by
            storefront. Apple bills you through your Apple ID. Payment is
            charged at the end of a free trial, if one applies, or at purchase.
            Subscriptions renew automatically unless you cancel at least 24
            hours before the end of the current period. Your account is charged
            for renewal within 24 hours before the period ends.
          </p>
          <p>
            Manage or cancel anytime in iOS Settings, Apple ID, Subscriptions,
            or on{" "}
            <a href="https://apps.apple.com/account/subscriptions">
              apps.apple.com/account/subscriptions
            </a>
            . Deleting the app does not cancel a subscription. Refunds, if any,
            are handled by Apple under Apple's refund rules. Protein Pic cannot
            process card refunds directly.
          </p>
          <p>
            Unused trial time is forfeited when you buy a subscription, unless
            Apple's rules say otherwise.
          </p>

          <h2>Your content</h2>
          <p>
            You keep ownership of meal photos and logs you create. You grant us
            a limited license to process that content so the app can estimate
            protein, show history, power groups you join, and keep the service
            running. Do not upload photos or text you do not have the right to
            use, and do not share other people's personal data in a group
            without permission.
          </p>

          <h2>Acceptable use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the app to harm, harass, or impersonate others.</li>
            <li>Probe, scrape, or overload the service.</li>
            <li>Misuse scans in a way that violates law or Apple's rules.</li>
            <li>Try to bypass a paywall, trial limit, or scan limit.</li>
          </ul>

          <h2>Groups</h2>
          <p>
            Groups are for accountability between people you choose. Content
            you share there may be visible to other members. We may remove a
            group or a member who breaks these Terms.
          </p>

          <h2>Availability</h2>
          <p>
            Features, scan limits, and coach suggestions may change. The app
            may be unavailable during maintenance or outages. We do not
            promise uninterrupted service or a specific accuracy rate for
            estimates.
          </p>

          <h2>Disclaimer</h2>
          <p>
            The app is provided "as is" and "as available." To the fullest
            extent allowed by law, we disclaim warranties of merchantability,
            fitness for a particular purpose, and non-infringement. Health and
            nutrition outcomes vary. You are responsible for how you use the
            estimates.
          </p>

          <h2>Limitation of liability</h2>
          <p>
            To the fullest extent allowed by law, {site.seller} and Protein Pic
            are not liable for indirect, incidental, special, consequential, or
            punitive damages, or for lost profits, data, or goodwill, arising
            from your use of the app. Our total liability for any claim is
            limited to the amount you paid for the app through Apple in the 12
            months before the claim, or ten US dollars if you paid nothing.
            Some places do not allow these limits. In those places, our
            liability is limited to the minimum the law requires.
          </p>

          <h2>Changes and termination</h2>
          <p>
            We may update these Terms and will change the date at the top when
            we do. We may suspend or stop the app, or your access, if you
            break these Terms or if we have to for legal or operational
            reasons. Provisions that should survive (including the license
            limits, disclaimers, and liability terms) will survive.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these Terms: contact {site.seller} through the{" "}
            <a href={site.appStoreUrl}>Protein Pic App Store listing</a>.
          </p>
        </LegalLayout>
      </main>
      <SiteFooter />
    </>
  );
}
